Test VAE model on random frame of random file in `record`

In [1]:
import numpy as np
import os
import re
import pickle
import json
import tensorflow as tf
import random
from gqcnn_network import GQCNN, reset_graph
from gqcnn_train import TensorDataset

In [2]:
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, edgeitems=6, linewidth=100, suppress=True)

In [3]:
os.environ["CUDA_VISIBLE_DEVICES"]="" # disable GPU

In [4]:
gqcnn = GQCNN()
reset_graph()
DATA_DIR = "/home/cjg429/Desktop/gqcnn-master/data/training/example_pj/tensors"
dataset = TensorDataset(DATA_DIR) 
seed = 0
np.random.seed(seed)
random.seed(seed)

INFO:tensorflow:Model using cpu.


In [5]:
for i in range(0, 100):
    images, poses, labels = dataset.sample()
    pred = gqcnn.predict(images, poses)
    print(pred, labels)

(array([[ 0.4688,  0.5312],
       [ 0.4848,  0.5152],
       [ 0.488 ,  0.512 ],
       [ 0.5491,  0.4509],
       [ 0.4926,  0.5074],
       [ 0.4655,  0.5345],
       [ 0.5016,  0.4984],
       [ 0.4771,  0.5229],
       [ 0.5017,  0.4983],
       [ 0.5205,  0.4795],
       [ 0.498 ,  0.502 ],
       [ 0.5132,  0.4868],
       [ 0.4957,  0.5043],
       [ 0.5033,  0.4967],
       [ 0.5043,  0.4957],
       [ 0.4806,  0.5194],
       [ 0.4986,  0.5014],
       [ 0.5004,  0.4996],
       [ 0.5091,  0.4909],
       [ 0.501 ,  0.499 ],
       [ 0.4539,  0.5461],
       [ 0.4809,  0.5191],
       [ 0.4928,  0.5072],
       [ 0.4728,  0.5272],
       [ 0.5115,  0.4885],
       [ 0.483 ,  0.517 ],
       [ 0.5   ,  0.5   ],
       [ 0.4862,  0.5138],
       [ 0.5354,  0.4646],
       [ 0.5157,  0.4843],
       [ 0.5292,  0.4708],
       [ 0.5074,  0.4926],
       [ 0.479 ,  0.521 ],
       [ 0.3953,  0.6047],
       [ 0.4431,  0.5569],
       [ 0.5377,  0.4623],
       [ 0.4492,  0.5508],


(array([[ 0.5362,  0.4638],
       [ 0.5721,  0.4279],
       [ 0.5683,  0.4317],
       [ 0.4821,  0.5179],
       [ 0.4805,  0.5195],
       [ 0.501 ,  0.499 ],
       [ 0.5164,  0.4836],
       [ 0.4841,  0.5159],
       [ 0.4553,  0.5447],
       [ 0.626 ,  0.374 ],
       [ 0.4765,  0.5235],
       [ 0.422 ,  0.578 ],
       [ 0.431 ,  0.569 ],
       [ 0.5478,  0.4522],
       [ 0.5151,  0.4849],
       [ 0.493 ,  0.507 ],
       [ 0.5596,  0.4404],
       [ 0.5218,  0.4782],
       [ 0.5993,  0.4007],
       [ 0.4276,  0.5724],
       [ 0.4906,  0.5094],
       [ 0.5708,  0.4292],
       [ 0.4839,  0.5161],
       [ 0.4709,  0.5291],
       [ 0.503 ,  0.497 ],
       [ 0.5017,  0.4983],
       [ 0.4135,  0.5865],
       [ 0.3944,  0.6056],
       [ 0.536 ,  0.464 ],
       [ 0.4102,  0.5898],
       [ 0.4687,  0.5313],
       [ 0.4862,  0.5138],
       [ 0.5088,  0.4912],
       [ 0.5668,  0.4332],
       [ 0.4623,  0.5377],
       [ 0.5404,  0.4596],
       [ 0.4635,  0.5365],


(array([[ 0.4862,  0.5138],
       [ 0.51  ,  0.49  ],
       [ 0.4909,  0.5091],
       [ 0.503 ,  0.497 ],
       [ 0.4814,  0.5186],
       [ 0.502 ,  0.498 ],
       [ 0.5094,  0.4906],
       [ 0.4874,  0.5126],
       [ 0.4906,  0.5094],
       [ 0.4989,  0.5011],
       [ 0.5038,  0.4962],
       [ 0.4509,  0.5491],
       [ 0.4928,  0.5072],
       [ 0.5019,  0.4981],
       [ 0.4977,  0.5023],
       [ 0.5011,  0.4989],
       [ 0.5024,  0.4976],
       [ 0.486 ,  0.514 ],
       [ 0.4984,  0.5016],
       [ 0.4807,  0.5193],
       [ 0.4964,  0.5036],
       [ 0.5123,  0.4877],
       [ 0.4891,  0.5109],
       [ 0.4945,  0.5055],
       [ 0.4934,  0.5066],
       [ 0.5068,  0.4932],
       [ 0.4923,  0.5077],
       [ 0.5054,  0.4946],
       [ 0.4828,  0.5172],
       [ 0.4911,  0.5089],
       [ 0.5078,  0.4922],
       [ 0.4888,  0.5112],
       [ 0.4967,  0.5033],
       [ 0.5203,  0.4797],
       [ 0.489 ,  0.511 ],
       [ 0.4945,  0.5055],
       [ 0.5105,  0.4895],


(array([[ 0.4569,  0.5431],
       [ 0.5027,  0.4973],
       [ 0.4894,  0.5106],
       [ 0.4651,  0.5349],
       [ 0.5164,  0.4836],
       [ 0.4952,  0.5048],
       [ 0.5036,  0.4964],
       [ 0.4928,  0.5072],
       [ 0.4856,  0.5144],
       [ 0.4823,  0.5177],
       [ 0.507 ,  0.493 ],
       [ 0.516 ,  0.484 ],
       [ 0.4804,  0.5196],
       [ 0.4624,  0.5376],
       [ 0.4896,  0.5104],
       [ 0.4935,  0.5065],
       [ 0.4861,  0.5139],
       [ 0.5112,  0.4888],
       [ 0.5023,  0.4977],
       [ 0.5134,  0.4866],
       [ 0.4946,  0.5054],
       [ 0.4897,  0.5103],
       [ 0.4893,  0.5107],
       [ 0.4905,  0.5095],
       [ 0.5062,  0.4938],
       [ 0.4967,  0.5033],
       [ 0.4981,  0.5019],
       [ 0.492 ,  0.508 ],
       [ 0.5418,  0.4582],
       [ 0.5293,  0.4707],
       [ 0.5202,  0.4798],
       [ 0.5107,  0.4893],
       [ 0.4853,  0.5147],
       [ 0.4903,  0.5097],
       [ 0.5047,  0.4953],
       [ 0.4811,  0.5189],
       [ 0.5137,  0.4863],


(array([[ 0.4883,  0.5117],
       [ 0.5   ,  0.5   ],
       [ 0.5061,  0.4939],
       [ 0.5117,  0.4883],
       [ 0.5191,  0.4809],
       [ 0.5157,  0.4843],
       [ 0.4814,  0.5186],
       [ 0.5069,  0.4931],
       [ 0.4942,  0.5058],
       [ 0.4922,  0.5078],
       [ 0.4922,  0.5078],
       [ 0.5001,  0.4999],
       [ 0.4913,  0.5087],
       [ 0.5115,  0.4885],
       [ 0.4877,  0.5123],
       [ 0.5073,  0.4927],
       [ 0.4956,  0.5044],
       [ 0.5085,  0.4915],
       [ 0.503 ,  0.497 ],
       [ 0.4948,  0.5052],
       [ 0.5111,  0.4889],
       [ 0.508 ,  0.492 ],
       [ 0.5046,  0.4954],
       [ 0.4969,  0.5031],
       [ 0.5072,  0.4928],
       [ 0.5056,  0.4944],
       [ 0.5022,  0.4978],
       [ 0.4841,  0.5159],
       [ 0.4939,  0.5061],
       [ 0.5033,  0.4967],
       [ 0.5129,  0.4871],
       [ 0.4893,  0.5107],
       [ 0.5112,  0.4888],
       [ 0.5025,  0.4975],
       [ 0.5037,  0.4963],
       [ 0.4923,  0.5077],
       [ 0.4911,  0.5089],


(array([[ 0.3788,  0.6212],
       [ 0.4435,  0.5565],
       [ 0.4885,  0.5115],
       [ 0.4818,  0.5182],
       [ 0.4971,  0.5029],
       [ 0.4668,  0.5332],
       [ 0.5292,  0.4708],
       [ 0.4102,  0.5898],
       [ 0.4464,  0.5536],
       [ 0.4605,  0.5395],
       [ 0.4068,  0.5932],
       [ 0.4776,  0.5224],
       [ 0.4074,  0.5926],
       [ 0.4538,  0.5462],
       [ 0.468 ,  0.532 ],
       [ 0.452 ,  0.548 ],
       [ 0.5289,  0.4711],
       [ 0.4739,  0.5261],
       [ 0.4364,  0.5636],
       [ 0.4981,  0.5019],
       [ 0.443 ,  0.557 ],
       [ 0.4948,  0.5052],
       [ 0.4691,  0.5309],
       [ 0.4199,  0.5801],
       [ 0.4781,  0.5219],
       [ 0.501 ,  0.499 ],
       [ 0.492 ,  0.508 ],
       [ 0.5247,  0.4753],
       [ 0.4687,  0.5313],
       [ 0.543 ,  0.457 ],
       [ 0.5113,  0.4887],
       [ 0.4262,  0.5738],
       [ 0.4774,  0.5226],
       [ 0.3891,  0.6109],
       [ 0.4997,  0.5003],
       [ 0.4477,  0.5523],
       [ 0.4841,  0.5159],


(array([[ 0.4796,  0.5204],
       [ 0.472 ,  0.528 ],
       [ 0.5422,  0.4578],
       [ 0.4949,  0.5051],
       [ 0.5114,  0.4886],
       [ 0.4821,  0.5179],
       [ 0.5277,  0.4723],
       [ 0.4991,  0.5009],
       [ 0.4926,  0.5074],
       [ 0.5177,  0.4823],
       [ 0.4924,  0.5076],
       [ 0.4826,  0.5174],
       [ 0.4916,  0.5084],
       [ 0.525 ,  0.475 ],
       [ 0.4751,  0.5249],
       [ 0.5267,  0.4733],
       [ 0.535 ,  0.465 ],
       [ 0.4584,  0.5416],
       [ 0.4885,  0.5115],
       [ 0.5082,  0.4918],
       [ 0.5609,  0.4391],
       [ 0.4147,  0.5853],
       [ 0.4758,  0.5242],
       [ 0.5097,  0.4903],
       [ 0.4495,  0.5505],
       [ 0.4624,  0.5376],
       [ 0.493 ,  0.507 ],
       [ 0.4897,  0.5103],
       [ 0.4732,  0.5268],
       [ 0.4097,  0.5903],
       [ 0.4606,  0.5394],
       [ 0.4424,  0.5576],
       [ 0.512 ,  0.488 ],
       [ 0.4808,  0.5192],
       [ 0.4624,  0.5376],
       [ 0.4701,  0.5299],
       [ 0.4304,  0.5696],


(array([[ 0.4011,  0.5989],
       [ 0.4891,  0.5109],
       [ 0.3834,  0.6166],
       [ 0.5403,  0.4597],
       [ 0.4448,  0.5552],
       [ 0.4343,  0.5657],
       [ 0.472 ,  0.528 ],
       [ 0.4677,  0.5323],
       [ 0.423 ,  0.577 ],
       [ 0.5146,  0.4854],
       [ 0.4916,  0.5084],
       [ 0.398 ,  0.602 ],
       [ 0.5062,  0.4938],
       [ 0.5068,  0.4932],
       [ 0.4102,  0.5898],
       [ 0.4618,  0.5382],
       [ 0.4887,  0.5113],
       [ 0.4029,  0.5971],
       [ 0.4932,  0.5068],
       [ 0.4958,  0.5042],
       [ 0.4934,  0.5066],
       [ 0.4442,  0.5558],
       [ 0.4436,  0.5564],
       [ 0.4684,  0.5316],
       [ 0.3969,  0.6031],
       [ 0.4671,  0.5329],
       [ 0.5441,  0.4559],
       [ 0.4188,  0.5812],
       [ 0.4557,  0.5443],
       [ 0.4997,  0.5003],
       [ 0.5066,  0.4934],
       [ 0.488 ,  0.512 ],
       [ 0.4832,  0.5168],
       [ 0.4872,  0.5128],
       [ 0.5557,  0.4443],
       [ 0.4543,  0.5457],
       [ 0.4247,  0.5753],


(array([[ 0.4969,  0.5031],
       [ 0.3654,  0.6346],
       [ 0.5162,  0.4838],
       [ 0.4695,  0.5305],
       [ 0.431 ,  0.569 ],
       [ 0.4243,  0.5757],
       [ 0.5146,  0.4854],
       [ 0.3597,  0.6403],
       [ 0.4967,  0.5033],
       [ 0.5131,  0.4869],
       [ 0.3648,  0.6352],
       [ 0.5464,  0.4536],
       [ 0.4567,  0.5433],
       [ 0.5436,  0.4564],
       [ 0.457 ,  0.543 ],
       [ 0.4916,  0.5084],
       [ 0.445 ,  0.555 ],
       [ 0.3893,  0.6107],
       [ 0.5199,  0.4801],
       [ 0.5893,  0.4107],
       [ 0.4646,  0.5354],
       [ 0.5066,  0.4934],
       [ 0.5753,  0.4247],
       [ 0.4795,  0.5205],
       [ 0.4898,  0.5102],
       [ 0.4454,  0.5546],
       [ 0.5105,  0.4895],
       [ 0.4677,  0.5323],
       [ 0.5017,  0.4983],
       [ 0.4709,  0.5291],
       [ 0.4825,  0.5175],
       [ 0.4967,  0.5033],
       [ 0.4973,  0.5027],
       [ 0.4685,  0.5315],
       [ 0.4926,  0.5074],
       [ 0.4863,  0.5137],
       [ 0.4644,  0.5356],


(array([[ 0.4803,  0.5197],
       [ 0.5089,  0.4911],
       [ 0.4662,  0.5338],
       [ 0.4765,  0.5235],
       [ 0.4515,  0.5485],
       [ 0.5101,  0.4899],
       [ 0.481 ,  0.519 ],
       [ 0.5021,  0.4979],
       [ 0.396 ,  0.604 ],
       [ 0.4414,  0.5586],
       [ 0.5231,  0.4769],
       [ 0.5495,  0.4505],
       [ 0.5584,  0.4416],
       [ 0.4945,  0.5055],
       [ 0.4798,  0.5202],
       [ 0.4816,  0.5184],
       [ 0.4754,  0.5246],
       [ 0.4581,  0.5419],
       [ 0.5804,  0.4196],
       [ 0.5157,  0.4843],
       [ 0.443 ,  0.557 ],
       [ 0.518 ,  0.482 ],
       [ 0.5407,  0.4593],
       [ 0.4694,  0.5306],
       [ 0.519 ,  0.481 ],
       [ 0.5603,  0.4397],
       [ 0.5032,  0.4968],
       [ 0.5044,  0.4956],
       [ 0.4704,  0.5296],
       [ 0.4774,  0.5226],
       [ 0.4942,  0.5058],
       [ 0.5056,  0.4944],
       [ 0.4536,  0.5464],
       [ 0.5076,  0.4924],
       [ 0.5212,  0.4788],
       [ 0.6232,  0.3768],
       [ 0.4809,  0.5191],


(array([[ 0.4774,  0.5226],
       [ 0.4902,  0.5098],
       [ 0.5058,  0.4942],
       [ 0.5   ,  0.5   ],
       [ 0.5092,  0.4908],
       [ 0.493 ,  0.507 ],
       [ 0.4698,  0.5302],
       [ 0.5081,  0.4919],
       [ 0.4366,  0.5634],
       [ 0.4868,  0.5132],
       [ 0.4967,  0.5033],
       [ 0.5258,  0.4742],
       [ 0.4744,  0.5256],
       [ 0.5128,  0.4872],
       [ 0.3807,  0.6193],
       [ 0.4818,  0.5182],
       [ 0.4661,  0.5339],
       [ 0.4352,  0.5648],
       [ 0.4899,  0.5101],
       [ 0.416 ,  0.584 ],
       [ 0.4697,  0.5303],
       [ 0.4958,  0.5042],
       [ 0.5367,  0.4633],
       [ 0.4926,  0.5074],
       [ 0.487 ,  0.513 ],
       [ 0.4788,  0.5212],
       [ 0.4655,  0.5345],
       [ 0.4584,  0.5416],
       [ 0.4894,  0.5106],
       [ 0.4824,  0.5176],
       [ 0.522 ,  0.478 ],
       [ 0.5344,  0.4656],
       [ 0.4421,  0.5579],
       [ 0.4381,  0.5619],
       [ 0.4833,  0.5167],
       [ 0.5297,  0.4703],
       [ 0.4679,  0.5321],


(array([[ 0.4733,  0.5267],
       [ 0.521 ,  0.479 ],
       [ 0.456 ,  0.544 ],
       [ 0.4899,  0.5101],
       [ 0.4947,  0.5053],
       [ 0.4668,  0.5332],
       [ 0.497 ,  0.503 ],
       [ 0.5069,  0.4931],
       [ 0.4599,  0.5401],
       [ 0.5508,  0.4492],
       [ 0.474 ,  0.526 ],
       [ 0.5093,  0.4907],
       [ 0.5048,  0.4952],
       [ 0.4867,  0.5133],
       [ 0.4927,  0.5073],
       [ 0.4773,  0.5227],
       [ 0.4623,  0.5377],
       [ 0.515 ,  0.485 ],
       [ 0.4766,  0.5234],
       [ 0.5132,  0.4868],
       [ 0.4965,  0.5035],
       [ 0.4746,  0.5254],
       [ 0.5125,  0.4875],
       [ 0.5319,  0.4681],
       [ 0.5012,  0.4988],
       [ 0.5483,  0.4517],
       [ 0.442 ,  0.558 ],
       [ 0.5092,  0.4908],
       [ 0.4945,  0.5055],
       [ 0.4811,  0.5189],
       [ 0.5141,  0.4859],
       [ 0.4705,  0.5295],
       [ 0.5458,  0.4542],
       [ 0.4744,  0.5256],
       [ 0.5541,  0.4459],
       [ 0.5157,  0.4843],
       [ 0.4853,  0.5147],


(array([[ 0.4543,  0.5457],
       [ 0.4672,  0.5328],
       [ 0.5439,  0.4561],
       [ 0.4505,  0.5495],
       [ 0.4802,  0.5198],
       [ 0.4951,  0.5049],
       [ 0.5131,  0.4869],
       [ 0.5065,  0.4935],
       [ 0.4874,  0.5126],
       [ 0.4798,  0.5202],
       [ 0.5313,  0.4687],
       [ 0.5305,  0.4695],
       [ 0.4845,  0.5155],
       [ 0.4787,  0.5213],
       [ 0.5161,  0.4839],
       [ 0.5031,  0.4969],
       [ 0.4906,  0.5094],
       [ 0.4853,  0.5147],
       [ 0.4975,  0.5025],
       [ 0.4811,  0.5189],
       [ 0.4674,  0.5326],
       [ 0.539 ,  0.461 ],
       [ 0.4349,  0.5651],
       [ 0.4751,  0.5249],
       [ 0.3889,  0.6111],
       [ 0.4951,  0.5049],
       [ 0.5068,  0.4932],
       [ 0.4881,  0.5119],
       [ 0.4811,  0.5189],
       [ 0.5079,  0.4921],
       [ 0.5003,  0.4997],
       [ 0.521 ,  0.479 ],
       [ 0.4803,  0.5197],
       [ 0.5458,  0.4542],
       [ 0.4999,  0.5001],
       [ 0.4562,  0.5438],
       [ 0.5107,  0.4893],


(array([[ 0.4968,  0.5032],
       [ 0.5147,  0.4853],
       [ 0.5178,  0.4822],
       [ 0.4944,  0.5056],
       [ 0.4577,  0.5423],
       [ 0.4381,  0.5619],
       [ 0.43  ,  0.57  ],
       [ 0.373 ,  0.627 ],
       [ 0.3843,  0.6157],
       [ 0.488 ,  0.512 ],
       [ 0.539 ,  0.461 ],
       [ 0.5166,  0.4834],
       [ 0.4241,  0.5759],
       [ 0.4547,  0.5453],
       [ 0.4628,  0.5372],
       [ 0.4378,  0.5622],
       [ 0.505 ,  0.495 ],
       [ 0.4655,  0.5345],
       [ 0.496 ,  0.504 ],
       [ 0.48  ,  0.52  ],
       [ 0.4963,  0.5037],
       [ 0.4507,  0.5493],
       [ 0.4966,  0.5034],
       [ 0.4011,  0.5989],
       [ 0.4981,  0.5019],
       [ 0.5273,  0.4727],
       [ 0.6827,  0.3173],
       [ 0.4938,  0.5062],
       [ 0.3782,  0.6218],
       [ 0.5306,  0.4694],
       [ 0.4569,  0.5431],
       [ 0.4715,  0.5285],
       [ 0.4291,  0.5709],
       [ 0.4294,  0.5706],
       [ 0.4695,  0.5305],
       [ 0.5054,  0.4946],
       [ 0.4975,  0.5025],


(array([[ 0.4602,  0.5398],
       [ 0.4946,  0.5054],
       [ 0.5035,  0.4965],
       [ 0.5868,  0.4132],
       [ 0.5073,  0.4927],
       [ 0.4987,  0.5013],
       [ 0.5049,  0.4951],
       [ 0.4742,  0.5258],
       [ 0.5118,  0.4882],
       [ 0.4926,  0.5074],
       [ 0.4743,  0.5257],
       [ 0.4717,  0.5283],
       [ 0.4965,  0.5035],
       [ 0.4745,  0.5255],
       [ 0.4995,  0.5005],
       [ 0.4974,  0.5026],
       [ 0.4898,  0.5102],
       [ 0.4835,  0.5165],
       [ 0.5834,  0.4166],
       [ 0.503 ,  0.497 ],
       [ 0.4954,  0.5046],
       [ 0.5045,  0.4955],
       [ 0.4953,  0.5047],
       [ 0.4634,  0.5366],
       [ 0.4851,  0.5149],
       [ 0.5284,  0.4716],
       [ 0.5083,  0.4917],
       [ 0.4762,  0.5238],
       [ 0.4954,  0.5046],
       [ 0.4251,  0.5749],
       [ 0.44  ,  0.56  ],
       [ 0.4825,  0.5175],
       [ 0.5083,  0.4917],
       [ 0.5051,  0.4949],
       [ 0.4898,  0.5102],
       [ 0.5088,  0.4912],
       [ 0.4901,  0.5099],


(array([[ 0.573 ,  0.427 ],
       [ 0.5198,  0.4802],
       [ 0.5045,  0.4955],
       [ 0.5137,  0.4863],
       [ 0.5607,  0.4393],
       [ 0.4299,  0.5701],
       [ 0.4798,  0.5202],
       [ 0.5864,  0.4136],
       [ 0.451 ,  0.549 ],
       [ 0.5119,  0.4881],
       [ 0.5433,  0.4567],
       [ 0.5261,  0.4739],
       [ 0.4593,  0.5407],
       [ 0.5011,  0.4989],
       [ 0.4827,  0.5173],
       [ 0.4391,  0.5609],
       [ 0.6163,  0.3837],
       [ 0.5089,  0.4911],
       [ 0.48  ,  0.52  ],
       [ 0.5098,  0.4902],
       [ 0.4575,  0.5425],
       [ 0.565 ,  0.435 ],
       [ 0.5331,  0.4669],
       [ 0.5351,  0.4649],
       [ 0.5573,  0.4427],
       [ 0.5547,  0.4453],
       [ 0.5314,  0.4686],
       [ 0.5915,  0.4085],
       [ 0.4745,  0.5255],
       [ 0.4626,  0.5374],
       [ 0.5298,  0.4702],
       [ 0.5199,  0.4801],
       [ 0.499 ,  0.501 ],
       [ 0.4879,  0.5121],
       [ 0.4713,  0.5287],
       [ 0.526 ,  0.474 ],
       [ 0.5171,  0.4829],


(array([[ 0.4864,  0.5136],
       [ 0.4558,  0.5442],
       [ 0.4725,  0.5275],
       [ 0.5029,  0.4971],
       [ 0.5307,  0.4693],
       [ 0.4651,  0.5349],
       [ 0.4801,  0.5199],
       [ 0.4737,  0.5263],
       [ 0.5075,  0.4925],
       [ 0.4153,  0.5847],
       [ 0.4518,  0.5482],
       [ 0.4354,  0.5646],
       [ 0.3733,  0.6267],
       [ 0.4557,  0.5443],
       [ 0.5171,  0.4829],
       [ 0.4623,  0.5377],
       [ 0.4766,  0.5234],
       [ 0.4482,  0.5518],
       [ 0.4432,  0.5568],
       [ 0.4564,  0.5436],
       [ 0.4877,  0.5123],
       [ 0.4513,  0.5487],
       [ 0.4459,  0.5541],
       [ 0.4882,  0.5118],
       [ 0.4861,  0.5139],
       [ 0.4869,  0.5131],
       [ 0.4629,  0.5371],
       [ 0.4941,  0.5059],
       [ 0.5164,  0.4836],
       [ 0.496 ,  0.504 ],
       [ 0.5029,  0.4971],
       [ 0.4355,  0.5645],
       [ 0.5254,  0.4746],
       [ 0.4389,  0.5611],
       [ 0.5191,  0.4809],
       [ 0.4311,  0.5689],
       [ 0.5024,  0.4976],


(array([[ 0.5011,  0.4989],
       [ 0.5013,  0.4987],
       [ 0.5348,  0.4652],
       [ 0.5131,  0.4869],
       [ 0.4879,  0.5121],
       [ 0.4941,  0.5059],
       [ 0.5006,  0.4994],
       [ 0.4989,  0.5011],
       [ 0.5045,  0.4955],
       [ 0.4737,  0.5263],
       [ 0.4995,  0.5005],
       [ 0.5228,  0.4772],
       [ 0.501 ,  0.499 ],
       [ 0.4959,  0.5041],
       [ 0.4942,  0.5058],
       [ 0.5006,  0.4994],
       [ 0.4938,  0.5062],
       [ 0.4873,  0.5127],
       [ 0.4917,  0.5083],
       [ 0.4786,  0.5214],
       [ 0.5124,  0.4876],
       [ 0.4992,  0.5008],
       [ 0.4972,  0.5028],
       [ 0.4814,  0.5186],
       [ 0.4905,  0.5095],
       [ 0.5256,  0.4744],
       [ 0.4947,  0.5053],
       [ 0.5069,  0.4931],
       [ 0.527 ,  0.473 ],
       [ 0.492 ,  0.508 ],
       [ 0.4969,  0.5031],
       [ 0.4893,  0.5107],
       [ 0.501 ,  0.499 ],
       [ 0.5226,  0.4774],
       [ 0.4969,  0.5031],
       [ 0.4935,  0.5065],
       [ 0.4936,  0.5064],


(array([[ 0.5138,  0.4862],
       [ 0.4847,  0.5153],
       [ 0.5111,  0.4889],
       [ 0.4968,  0.5032],
       [ 0.4998,  0.5002],
       [ 0.4776,  0.5224],
       [ 0.4774,  0.5226],
       [ 0.503 ,  0.497 ],
       [ 0.4769,  0.5231],
       [ 0.4633,  0.5367],
       [ 0.4938,  0.5062],
       [ 0.4716,  0.5284],
       [ 0.4838,  0.5162],
       [ 0.4907,  0.5093],
       [ 0.4713,  0.5287],
       [ 0.4591,  0.5409],
       [ 0.5243,  0.4757],
       [ 0.4861,  0.5139],
       [ 0.4608,  0.5392],
       [ 0.5085,  0.4915],
       [ 0.4925,  0.5075],
       [ 0.4967,  0.5033],
       [ 0.458 ,  0.542 ],
       [ 0.4932,  0.5068],
       [ 0.4944,  0.5056],
       [ 0.5069,  0.4931],
       [ 0.482 ,  0.518 ],
       [ 0.5224,  0.4776],
       [ 0.482 ,  0.518 ],
       [ 0.4935,  0.5065],
       [ 0.5089,  0.4911],
       [ 0.5103,  0.4897],
       [ 0.4914,  0.5086],
       [ 0.5302,  0.4698],
       [ 0.4557,  0.5443],
       [ 0.4623,  0.5377],
       [ 0.4811,  0.5189],


(array([[ 0.4965,  0.5035],
       [ 0.4925,  0.5075],
       [ 0.4984,  0.5016],
       [ 0.4766,  0.5234],
       [ 0.4736,  0.5264],
       [ 0.4871,  0.5129],
       [ 0.4886,  0.5114],
       [ 0.4782,  0.5218],
       [ 0.5033,  0.4967],
       [ 0.4845,  0.5155],
       [ 0.459 ,  0.541 ],
       [ 0.502 ,  0.498 ],
       [ 0.5256,  0.4744],
       [ 0.5161,  0.4839],
       [ 0.5062,  0.4938],
       [ 0.4624,  0.5376],
       [ 0.5017,  0.4983],
       [ 0.5034,  0.4966],
       [ 0.4902,  0.5098],
       [ 0.4952,  0.5048],
       [ 0.5044,  0.4956],
       [ 0.5178,  0.4822],
       [ 0.4876,  0.5124],
       [ 0.474 ,  0.526 ],
       [ 0.4753,  0.5247],
       [ 0.5019,  0.4981],
       [ 0.5015,  0.4985],
       [ 0.5131,  0.4869],
       [ 0.4872,  0.5128],
       [ 0.4827,  0.5173],
       [ 0.5056,  0.4944],
       [ 0.507 ,  0.493 ],
       [ 0.4853,  0.5147],
       [ 0.4671,  0.5329],
       [ 0.4959,  0.5041],
       [ 0.493 ,  0.507 ],
       [ 0.5049,  0.4951],
